// AUTO-GENERATED by scripts/extract-glyphs.mjs — do not edit by hand.
// Exact Archivo Black outlines, design space: cap height = 760, baseline y = 760.

export type GlyphData = {
  d: string;
  advance: number;
  bbox: {x1: number; y1: number; x2: number; y2: number};
};

export const CAP_HEIGHT = 760;

export const GLYPH_R: GlyphData = {
  "d": "M803.08 233.08Q803.08 302.67 765.52 359.01Q727.97 415.35 656.16 441.86L656.16 441.86L825.17 760L551.22 760L416.45 482.73L325.87 482.73L325.87 760L81.74 760L81.74 0L546.80 0Q628.55 0 686.54 31.48Q744.53 62.97 773.81 116.54Q803.08 170.12 803.08 233.08L803.08 233.08ZM554.53 243.02Q554.53 213.20 534.65 193.31Q514.77 173.43 486.05 173.43L486.05 173.43L325.87 173.43L325.87 313.72L486.05 313.72Q514.77 313.72 534.65 293.28Q554.53 272.85 554.53 243.02L554.53 243.02Z",
  "advance": 859.4186046511626,
  "bbox": {
    "x1": 81.74418604651163,
    "y1": 0,
    "x2": 825.1744186046511,
    "y2": 760
  }
};

export const GLYPH_N: GlyphData = {
  "d": "M838.43 760L625.23 760L305.99 391.05L305.99 760L81.74 760L81.74 0L294.94 0L614.19 374.48L614.19 0L838.43 0L838.43 760Z",
  "advance": 920.1744186046509,
  "bbox": {
    "x1": 81.74418604651163,
    "y1": 0,
    "x2": 838.4302325581396,
    "y2": 760
  }
};
