/**
 * Extracts the exact "R" and "N" outlines from Archivo Black and writes them
 * as SVG path data into src/intro/glyphs.ts (design space: cap height = 760).
 *
 * Run once (output is committed): node scripts/extract-glyphs.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import opentype from 'opentype.js';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const fontPath = path.join(root, 'public/fonts/ArchivoBlack-Regular.ttf');

const font = opentype.loadSync(fontPath);
const unitsPerEm = font.unitsPerEm;
const capHeightUnits = font.tables.os2.sCapHeight ?? 700;

// Design space: capital letters are exactly 760 units tall, baseline at y=760.
const CAP = 760;
const fontSize = (CAP / capHeightUnits) * unitsPerEm;
const scale = fontSize / unitsPerEm;

const extract = (char) => {
  const glyph = font.charToGlyph(char);
  const p = glyph.getPath(0, CAP, fontSize);
  const bb = p.getBoundingBox();
  return {
    d: p.toPathData(2),
    advance: glyph.advanceWidth * scale,
    bbox: {x1: bb.x1, y1: bb.y1, x2: bb.x2, y2: bb.y2},
  };
};

const R = extract('R');
const N = extract('N');

const out = `// AUTO-GENERATED by scripts/extract-glyphs.mjs — do not edit by hand.
// Exact Archivo Black outlines, design space: cap height = 760, baseline y = 760.

export type GlyphData = {
  d: string;
  advance: number;
  bbox: {x1: number; y1: number; x2: number; y2: number};
};

export const CAP_HEIGHT = ${CAP};

export const GLYPH_R: GlyphData = ${JSON.stringify(R, null, 2)};

export const GLYPH_N: GlyphData = ${JSON.stringify(N, null, 2)};
`;

fs.writeFileSync(path.join(root, 'src/intro/glyphs.ts'), out);

console.log('unitsPerEm:', unitsPerEm, 'capHeight:', capHeightUnits, 'fontSize:', fontSize.toFixed(2));
console.log('R advance:', R.advance.toFixed(1), 'bbox:', JSON.stringify(R.bbox));
console.log('N advance:', N.advance.toFixed(1), 'bbox:', JSON.stringify(N.bbox));
console.log('Wrote src/intro/glyphs.ts');
